#lang racket
(define (cont-frac n d k)
  (define (cont-frac-iter n d k i)
    (if (= i k)
        (/ (n k) (d k))
        (/ (n i) (+ (d i) (cont-frac-iter n d k (+ i 1))))))
  (cont-frac-iter n d k 1))
(cont-frac (lambda (i) 1.0)
           (lambda (i)
             (if (= (remainder i 3) 2)
                 (/ (* 2 (+ i 1)) 3)
                 1.0))
           1000)
