#lang racket
(define (make-fixedpoint x y) (cons x y))
(define (x-fixedpoint fp) (car fp))
(define (y-fixedpoint fp) (cdr fp))
(define (make-margin length width) (cons length width))
(define (length-margin margin) (car margin))
(define (width-margin margin) (cdr margin))
(define (make-rectangle fixedpoint margin) (cons fixedpoint margin))
(define (fixedpoint-rectangle rectangle) (car rectangle))
(define (margin-rectangle rectangle) (cdr rectangle))
(define (get-area rectangle)
  (* (length-margin (margin-rectangle rectangle)) (width-margin (margin-rectangle rectangle))))
(define (get-circumference rectangle)
  (* (+ (length-margin (margin-rectangle rectangle)) (width-margin (margin-rectangle rectangle))) 2))
(get-area (make-rectangle (make-fixedpoint 0 0) (make-margin 5 7)))
(get-circumference (make-rectangle (make-fixedpoint 0 0) (make-margin 5 7)))