#lang racket
(define (square x)
  (* x x))
(define (square-tree-1 tree)
  (cond ((null? tree) null)
        ((not (pair? tree)) (* tree tree))
        (else (cons (square-tree-1 (car tree))
                    (square-tree-1 (cdr tree))))))
(square-tree-1 (list 1 (list 2 (list 3 4) 5) (list 6 7)))
(define (map proc items)
  (cond ((null? items) null)
        ((not (pair? items)) (proc items))
        (else (cons (map proc (car items))
                    (map proc (cdr items))))))
(define (square-tree-2 tree)
  (map square tree))
(square-tree-2 (list 1 (list 2 (list 3 4) 5) (list 6 7)))
(define (square-tree-3 tree)
  (cond ((null? tree) null)
        ((pair? tree) (map square tree))
        (else (cons (square-tree-3 (car tree))
                    (square-tree-3 (cdr tree))))))
(square-tree-3 (list 1 (list 2 (list 3 4) 5) (list 6 7)))